#!/bin/bash
# author: John Zlotek
# usage: installing python3 virtual environment with packages

command -v virtualenv >/dev/null || pip install virtualenv --user

virtualenv ./venv --python python3 || if [[ $(python --version | egrep '\s3' | wc -l) -eq 1 ]]; then
  virtualenv ./venv --python python
else
  echo "Please install Python 3"
fi

ACTIVATE_LOC="$(find ./venv -type f -name activate)"

source "$ACTIVATE_LOC"

if [[ -f requirements.txt ]]; then
  pip install -r requirements.txt
fi

if [[ -f package.json ]]; then
  command -v yarn || npm install yarn
  yarn
fi

echo "http://drexel-cs583-final.s3.us-east-2.amazonaws.com/model.zip" | python src/threaded_download.py -v -d ./src/trained_model --clobber\
    && python src/unzip_files.py src/trained_model/model.zip src/trained_model\
    && mv src/trained_model/result_Sony/* src/trained_model/.


echo "Done installing"
echo "Run \`source $ACTIVATE_LOC\` to enter the virtual environment"

